#!/usr/bin/env bash
export SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

# Down the last running theme
if [ -f "/tmp/leftwm-theme-down" ]; then
    /tmp/leftwm-theme-down
    rm /tmp/leftwm-theme-down
fi
ln -s $SCRIPTPATH/down /tmp/leftwm-theme-down

# diversity of apps to start
nm-applet &
xfce4-power-manager &
numlockx on &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
volumeicon &

# Set the theme.ron config
leftwm command "LoadTheme $SCRIPTPATH/theme.ron"

# Set background
if [ -x "$(command -v feh)" ]; then
  feh --randomize --bg-fill "$SCRIPTPATH"/wallpapers/*
fi

pkill polybar
echo "---" | tee -a ~/.cache/polybar-top.log ~/.cache/polybar-bottom.log
polybar top >>~/.cache/polybar-top.log 2>&1 &
polybar bottom >>~/.cache/polybar-bottom.log 2>&1 &
